### RECUPERAR TODAS LAS JUEGOS
GET http://localhost:1234/games

### RECUPERAR UN JUEGO POR ID
GET http://localhost:1234/games/d7e8ab2e-3c8d-11ef-9303-f02f7419c768

### BORRAR UN JUEGO POR ID
DELETE http://localhost:1234/games/0a2d176d-3c8e-11ef-9303-f02f7419c768

### CREAR UN JUEGO CON POST
POST http://localhost:1234/games
Content-Type: application/json

{
  "title": "Lorem, ipsum dolor",
  "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic delectus",
  "category_id": 1,
  "liked": 212,
  "download": 166,
  "price": 15.45,
  "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg"
}

### ACTUALIZAR UN JUEVO -> (solo una parte de el)
PATCH http://localhost:1234/games/d7e8ab2e-3c8d-11ef-9303-f02f7419c768
Content-Type: application/json

{
  "title": "Mortal Kombat",
  "description": "Lorem ipsum dolor",
  "category_id": 1,
  "price": 12.22
}

### ACTUALIZAR COMPLETAMENTE UN RECURSO
PUT http://localhost:1234/games/d7e8ab2e-3c8d-11ef-9303-f02f7419c768
Content-Type: application/json

{
  "title": "Updated Title",
  "description": "Updated Description xdxd",
  "category_id": 1,
  "liked": 300,
  "download": 200,
  "price": 20.00,
  "poster": "https://updatedimage.url"
}
